# -*- coding: utf-8 -*-
"""PROYECTIL_TAREA_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Of__wCNAAhaC-2rD2JzGQxWLIIGIURHF
"""

!apt-get -y -qq install gfortran
!gfortran --version

# Commented out IPython magic to ensure Python compatibility.
# %%writefile projectile.f90
# program projectilemax
#   ! Este programa calcula la altura máxima de un proyectil
#   ! Restringe la velocidad a valores positivos y el ángulo entre 0 y 180
#   ! respecto a la horizontal
# 
#     implicit none ! Declara las variables de forma explícita
#     real      :: v0, theta_grad, theta_rad, h_max, pi, g
# 
#     logical   :: entrada_valida ! Para el ciclo do while
# 
# 
#   ! Declaración de constantes
# 
#     pi = 3.14159265359
#     g = 9.8
#     entrada_valida = .false. ! Inicializa el condicional en falso
# 
# 
#   ! Ciclo do while para la entrada de datos, validando que cumplan las
#   ! restricciones
# 
#     do while (.not. entrada_valida)
#         print *, "Ingresa la velocidad inicial (m/s) del proyectil (debe ser postiva):"
#         read *, v0
# 
#         if (v0 >= 0) then
#             entrada_valida = .true.
#         else
#             print *, "Error: La velocidad DEBE ser positiva. Intenta de nuevo."
#         end if
#     end do
# 
#     entrada_valida = .false. ! Vuelve a inicializar el condicional en falso
# 
#     do while (.not. entrada_valida)
#         print *, "Ingresa el ángulo en grados respecto a la horizontal del proyectil (debe estar entre 0 y 180):"
#         read *, theta_grad
# 
#         if (theta_grad >= 0 .and. theta_grad <= 180) then
#             entrada_valida = .true.
#         else
#             print *, "Error: El ángulo DEBE estar entre los rangos indicados. Intenta de nuevo."
#         end if
#     end do
# 
#     theta_rad = pi * theta_grad / 180.0 ! Convierte el ángulo a radianes
#     ! Fórmula para calcular la altura máxima del proyectil
#     h_max = (v0 * v0 * sin(theta_rad) * sin(theta_rad)) / (2.0*g)
# 
#   ! Imprime el resultado
#     print *, "La altura máxima del proyectil es de = ", h_max, "metros"
# 
#     open(unit=10, file="resultado.txt", status="replace")
#     write(10, *) h_max
#     close(10)
# 
# end program projectilemax

!gfortran projectile.f90 -o proy -O2
!./proy

# Verificación PASS/FAIL manual con tolerancia
with open("resultado.txt") as f:
    resultado = float(f.read().strip())

esperado = 4.9000
tolerancia = 1e-3  # Define el margen de error permitido (0.001)

if abs(resultado - esperado) < tolerancia:
    print(f"PASS: resultado = {resultado}")
else:
    print(f"FAIL: se obtuvo {resultado}, se esperaba {esperado}")